More precise error messages for moving unmanaged resource
ClusterLabs/pcs pull request #573
Opened 2022-10-17 09:29 UTC by F16shen

In my case, I don't have any constraint in the cluster , so the error message looks quite confusing.
```
Error: Unable to move resource 'xxxxx' using a location constraint. Current location of the resource may be affected by some other constraint.
```

Does this needs a test case?

2022-10-17 09:45 UTC, tomjelinek commented
test this please

2022-10-17 12:44 UTC, ondrejmular requested changes
Thank you for the patch. I like the idea.

Could you please also add a test coverage for the new code? Adding a test-case to `pcs_test.tier0.lib.commands.resource.test_resource_move_autoclean.MoveAutocleanValidations` should be sufficient.

2022-10-17 12:44 UTC, ondrejmular commented on pcs/lib/commands/resource.py
> +            ReportItem.warning(
This should be an error as we are basically sure move will fail.

2022-10-17 12:44 UTC, ondrejmular commented on pcs/lib/commands/resource.py
> +    cluster_state=env.get_cluster_state()
```suggestion
    cluster_state = env.get_cluster_state()
```

We use https://github.com/psf/black for python code formatting. Make sure that you run `make check` before committing changes. To enable all development related checks (e.g. pylint, mypy, black and typos checks) run `./configure` with option `--enable-dev-tests`. See [CONTRIBUTING.md](https://github.com/ClusterLabs/pcs/blob/main/CONTRIBUTING.md) for more details.

You can use `make black` to automatically format all python code.

2022-10-18 07:53 UTC, F16shen commented
Thank you for the reply. I have fixed issue you mentioned @ondrejmular

2022-10-18 07:55 UTC, ondrejmular approved these changes

2022-10-18 14:42 UTC, tomjelinek commented
retest this please

2022-10-19 07:38 UTC, merged