replace Iterable[str] type hints
ClusterLabs/pcs pull request #623
Opened 2023-01-27 10:02 UTC by tomjelinek

2023-01-30 14:56 UTC, ondrejmular requested changes

2023-01-30 14:56 UTC, ondrejmular commented on pcs_test/tier0/test_lint.py
> +)
This will not work with `--installed` option. IMHO the easiest way to solve this would be to use `import pcs; pcs.__path__`

2023-01-30 14:56 UTC, ondrejmular commented on pcs_test/tier0/test_lint.py
> +                        r"\b(collection|iterable|sequence)\[[^][]*str",
maybe this way it will be easier to read `\b(collection|iterable|sequence)\[[^\[\]]*str`

2023-01-31 13:10 UTC, tomjelinek commented
retest this please

2023-02-02 06:38 UTC, ondrejmular approved these changes

2023-02-02 06:41 UTC, merged