allow creating qdevice certs on the local node only
ClusterLabs/pcs pull request #639
Opened 2023-02-20 09:17 UTC by tomjelinek

2023-02-20 12:24 UTC, tomjelinek commented
retest this please

2023-02-21 08:46 UTC, ondrejmular requested changes

2023-02-21 08:46 UTC, ondrejmular commented on pcs/lib/corosync/qdevice_net.py
> +        settings.corosync_qdevice_net_client_certs_dir,
Option `-L` could be added here at it is added everywhere. And `certutil_cmd` can be `tuple` instead of `list`.

2023-02-27 10:45 UTC, ondrejmular requested changes
File `pcs_test/tier0/cli/test_quorum.py` is not specified in `EXTRA_DIST` in `pcs_test/Makefile.am` file.

2023-02-27 11:37 UTC, ondrejmular approved these changes

2023-02-27 14:34 UTC, merged