add meta option usage for pcs resource clone
ClusterLabs/pcs pull request #648
Opened 2023-03-01 06:42 UTC by F16shen

fix https://bugzilla.redhat.com/show_bug.cgi?id=2168155
I'm not sure modify usage enough for this issue. The output looks like it adds meta properties for the clone, not the base resource. But to my understanding meta option is set for primitive resource

2023-03-20 11:42 UTC, tomjelinek requested changes
The usage is correct, there is nothing to be fixed in there. What's wrong is parsing of `pcs resource clone` arguments. See [comment 1](https://bugzilla.redhat.com/show_bug.cgi?id=2168155#c1) in the original bugzilla.

2023-04-06 11:09 UTC, tomjelinek commented
test this please

2023-04-06 12:32 UTC, tomjelinek requested changes
Thank you for updating the pull request. However, there are still issues which need to be resolved. Feel free to reach out to us if you need more guidance.

2023-04-06 12:32 UTC, tomjelinek commented on pcs/cli/resource/parse_args.py
> +        "clone_option": {},
This change is unnecessary, the arguments parsed into this key are really meta attributes of a clone.

2023-04-06 12:32 UTC, tomjelinek commented on pcs/cli/resource/parse_args.py
> +        )
For now, we need to allow `meta` keyword to maintain backward compatibility. So we cannot raise an exception here. Instead, print a deprecation warning using `pcs.cli.reports.output.deprecation_warning`.

2023-04-06 12:32 UTC, tomjelinek commented on pcs/cli/resource/parse_args.py
> +            "meta options is not supported in 'pcs resource clone' command"
This function doesn't know it is called from `pcs resource clone` command. In fact, it is being called from `pcs resource clone`, `pcs resource promotable` and `pcs resource update`. The message should not refer to any specific pcs command.

2023-04-06 12:32 UTC, tomjelinek commented on pcs/cli/resource/parse_args.py
> -            )
This check and the related exception is needed. It prevents command `pcs resource promotable resource-name promotable=false` to pass, as it is a mistake to create a promotable clone and set its promotable flag to false in one step.

2023-04-10 02:31 UTC, F16shen commented
Thanks for the comments. 
I only add a deprecated warning this time. Should I add tests as well?

2023-04-11 12:19 UTC, tomjelinek commented
test this please

2023-04-17 15:23 UTC, tomjelinek commented
test this please

2023-04-17 15:26 UTC, tomjelinek approved these changes
Thanks, this was it.

I just made sure that the deprecation warning doesn't get printed from `pcs resource update` command. And I updated tests and changelog, as there was not much to do.

2023-04-18 07:44 UTC, merged