move resource restart to pcs.lib
ClusterLabs/pcs pull request #839
Opened 2024-07-02 14:56 UTC by tomjelinek

2024-07-25 14:26 UTC, mirecheck requested changes

2024-07-25 14:26 UTC, mirecheck commented on pcs_test/tier0/lib/commands/resource/test_restart.py
this added file is missing in 'pcs_test/Makefile.am'

2024-07-29 13:08 UTC, tomjelinek commented
retest this please

2024-07-29 14:55 UTC, tomjelinek commented
retest this please

2024-07-30 07:42 UTC, tomjelinek commented
retest this please

2024-07-30 07:46 UTC, merged